[package]
name = "jeffrey/broadcaster"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
lemonsignal = "data-oriented-house/lemonsignal@1.10.0"
janitor = "howmanysmall/janitor@1.18.3"
